//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkData.Server.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OSecret> OSecrets { get; set; }
        public virtual DbSet<OToken> OTokens { get; set; }
        public virtual DbSet<XToken> XTokens { get; set; }
        public virtual DbSet<XUser> XUsers { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
