//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkData.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OToken
    {
        public string Key { get; set; }
        public string Token { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual OSecret OSecret { get; set; }
    }
}
