//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkData.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUser
    {
        public string Description { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLogin { get; set; }
    
        public virtual XToken XToken { get; set; }
    }
}
